/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "surface-container-low": "#f2f3ff",
        secondary: "#712ae2",
        "on-tertiary-container": "#d7f6ff",
        "on-primary-fixed": "#00174b",
        "surface-container-highest": "#dae2fd",
        "surface-container": "#eaedff",
        "tertiary-fixed-dim": "#4cd7f6",
        "inverse-primary": "#b4c5ff",
        primary: "#004ac6",
        "on-tertiary-fixed": "#001f26",
        background: "#faf8ff",
        "tertiary-container": "#00788c",
        "on-surface": "#131b2e",
        "outline-variant": "#c3c6d7",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed": "#acedff",
        "secondary-fixed-dim": "#d2bbff",
        "inverse-surface": "#283044",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#eaddff",
        tertiary: "#005e6e",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-secondary-fixed": "#25005a",
        "secondary-container": "#8a4cfc",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-fixed-variant": "#003ea8",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#5a00c6",
        outline: "#737686",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        surface: "#faf8ff",
        "on-surface-variant": "#434655",
        "on-secondary-container": "#fffbff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-container": "#eeefff",
        "on-background": "#131b2e",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "#d2d9f4",
        "surface-variant": "#dae2fd",

        // Original app colors (kept for the rest of the app)
        sidebar: '#F7F8FC',
        border: '#E4E6F0',
        'ai-message': '#FFFFFF',
        'user-message': '#2541D6',
        accent: '#2541D6',
        'accent-hover': '#1e3bb8',
        'text-primary': '#0F1229',
        'text-secondary': '#5B5F73',
        'input-bg': '#FFFFFF',
        'hover-bg': '#E4E6F0',
        navy: '#0F1229',
        indigo: '#6B21D9',
        blue: '#2541D6',
        violet: '#8B5CF6',
        sky: '#4F7CFF',
        'white-10': 'rgba(255, 255, 255, 0.1)',
        'white-20': 'rgba(255, 255, 255, 0.2)',
        'white-40': 'rgba(255, 255, 255, 0.4)',
        'white-60': 'rgba(255, 255, 255, 0.6)',
        'white-70': 'rgba(255, 255, 255, 0.7)',
        'white-80': 'rgba(255, 255, 255, 0.8)',
        'black-10': 'rgba(15, 18, 41, 0.1)',
        'black-20': 'rgba(15, 18, 41, 0.2)',
        brand: {
          DEFAULT: '#2541D6',
          hover: '#1e3bb8',
          indigo: '#6B21D9',
          navy: '#0F1229',
          violet: '#8B5CF6',
          sky: '#4F7CFF',
          50: '#EEF2FF',
          100: '#E0E7FF',
          200: '#C7D2FE',
          300: '#A5B4FC',
          400: '#4F7CFF',
          500: '#2541D6',
          600: '#6B21D9',
          700: '#5B21D9',
          800: '#4B1FA3',
          900: '#3B1A7D',
          950: '#0F1229'
        },
        violet: {
          50: '#F5F3FF',
          100: '#EDE9FE',
          200: '#DDD6FE',
          300: '#C4B5FD',
          400: '#8B5CF6',
          500: '#6B21D9',
          600: '#5B1ED6',
          700: '#4B1AAF',
          800: '#3B1589',
          900: '#2D1064',
        },
        blue: {
          50: '#EEF2FF',
          100: '#E0E7FF',
          200: '#C7D2FE',
          300: '#A5B4FC',
          400: '#4F7CFF',
          500: '#2541D6',
          600: '#1e3bb8',
          700: '#1a32a3',
          800: '#152880',
          900: '#0F1A4D',
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem"
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        gutter: "24px"
      },
      fontFamily: {
        sans: ['Merienda', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        "display-lg": ["Merienda", "sans-serif"],
        "headline-sm": ["Merienda", "sans-serif"],
        "display-lg-mobile": ["Merienda", "sans-serif"],
        "body-md": ["Merienda", "sans-serif"],
        "label-sm": ["Merienda", "sans-serif"],
        "headline-md": ["Merienda", "sans-serif"],
        "label-md": ["Merienda", "sans-serif"],
        "body-lg": ["Merienda", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      },
      animation: {
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'typing': 'typing 1s steps(40, end)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        slideUp: {
          '0%': { opacity: 0, transform: 'translateY(10px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        typing: {
          'from': { width: '0' },
          'to': { width: '100%' },
        },
      },
    },
  },
  plugins: [],
}